// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEvent.proto

package com.exapmle.grpc.systemevent;

public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.exapmle.grpc.systemevent.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}