// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEvent.proto

package com.exapmle.grpc.systemevent;

public final class SystemEvent {
  private SystemEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_exapmle_grpc_systemevent_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_exapmle_grpc_systemevent_Ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_exapmle_grpc_systemevent_SystemEventMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_exapmle_grpc_systemevent_SystemEventMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021SystemEvent.proto\022\034com.exapmle.grpc.sy" +
      "stemevent\032\037google/protobuf/timestamp.pro" +
      "to\032\033google/protobuf/empty.proto\"\026\n\003Ack\022\017" +
      "\n\007message\030\001 \001(\t\"J\n\022SystemEventMessage\022\021\n" +
      "\ttimestamp\030\001 \001(\t\022\023\n\013serviceName\030\002 \001(\t\022\014\n" +
      "\004user\030\003 \001(\t2|\n\022SystemEventService\022f\n\017sav" +
      "eSystemEvent\0220.com.exapmle.grpc.systemev" +
      "ent.SystemEventMessage\032!.com.exapmle.grp" +
      "c.systemevent.AckB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_com_exapmle_grpc_systemevent_Ack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_exapmle_grpc_systemevent_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_exapmle_grpc_systemevent_Ack_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_exapmle_grpc_systemevent_SystemEventMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_exapmle_grpc_systemevent_SystemEventMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_exapmle_grpc_systemevent_SystemEventMessage_descriptor,
        new java.lang.String[] { "Timestamp", "ServiceName", "User", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
