// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEvent.proto

package com.exapmle.grpc.systemevent;

public interface SystemEventMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.exapmle.grpc.systemevent.SystemEventMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string timestamp = 1;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string serviceName = 2;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string user = 3;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();
}
